name: CI
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: .NET Setup
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Fetch submodules
      run: git submodule update --init --recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Navigate to workspace
      run: cd $GITHUB_WORKSPACE

    - name: Restore packages
      run: nuget restore UAssetGUI.sln

    - name: Build
      run: msbuild UAssetGUI.sln /p:Configuration=Release
    
    #- name: Navigate to workspace
    #  run: cd $GITHUB_WORKSPACE
      
    - name: Zip UAssetAPI artifact
      uses: TheDoctor0/zip-release@0.7.6
      with:
            filename: Artifacts/UAssetAPI.zip
            path: UAssetAPI/UAssetAPI/bin
            directory: .
    
    #- name: Navigate to workspace
    #  run: cd $GITHUB_WORKSPACE
      
    - name: Zip UAssetGUI artifact
      uses: TheDoctor0/zip-release@0.7.6
      with:
            filename: Artifacts/UAssetGUI.zip
            path: UAssetGUI/bin
            directory: .
    
    #- name: Navigate to workspace
    #  run: cd $GITHUB_WORKSPACE
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        path: Artifacts/*.zip
        if-no-files-found: error
