name: Update Submodules

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Git
        run: |
           git config --global user.email "actions@github.com"
           git config --global user.name "GitHub Actions"

      - name: Update submodules
        run: |
          git submodule update --init --recursive --remote UAssetAPI
          git add .
          git submodule update --init --recursive
          git commit -m "updated submodules"
          git push
        continue-on-error: true
